name: four_step_login
description: Four step login app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700

    - family: DMSans
      fonts:
          - asset: assets/fonts/DMSans-Variable.ttf
            style: normal
          - asset: assets/fonts/DMSans-Italic-Variable.ttf
            style: italic